Repository compucorp/uk.co.compucorp.civicrm.prospect, pull requests merged in 2020-06, with the labels that each got.

#61 CPS-4: Prospect Fixes and Enhancements
  CRM/Prospect/Form/Handler/OpenCase.php
  CRM/Prospect/ProspectCustomGroups.php
  CRM/Prospect/Setup/AddProspectCategoryCgExtendsValue.php
  CRM/Prospect/Setup/CreateProspectMenus.php
  CRM/Prospect/Setup/MoveCustomFieldsToProspecting.php
  CRM/Prospect/Setup/MoveCustomFieldsToWorkFlowCaseType.php
  CRM/Prospect/Setup/ProcessProspectCategoryForCustomGroupSupport.php
  CRM/Prospect/Uninstall/DeleteInstalledCustomGroups.php
  CRM/Prospect/Uninstall/DeleteProspectMenus.php
  CRM/Prospect/Upgrader.php
  CRM/Prospect/Upgrader/Steps/Step1003.php
  CRM/Prospect/Upgrader/Steps/Step1004.php
  prospect.php
  sql/auto_uninstall.sql
Labels: bug, enhancement

#62 RSE-1121: Release v2.0.0-beta.1
  info.xml
Labels: release

#63 ACU-103: Fix Issue With Installing Prospects On Some Sites
  CRM/Prospect/Upgrader.php
Labels: bug

#64 CPS-248: Fix security issues and unit tests
  .github/workflows/linters.yml
  .huskyrc
  .npmrc
  .nvmrc
  ang/test/global.js
  ang/test/karma.conf.js
  css/prospect.min.css.map
  package-lock.json
  package.json
Labels: bug

#65 CPS-248: Release v2.0.0-beta.2
  info.xml
Labels: release
